/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.BillDao;
import DAO.CategoryDao;
import DAO.FoodDao;
import DAO.TableDao;
import GUI.JPanelFood.Action;
import entity.Bill;
import entity.BillInfo;
import entity.Category;
import entity.Food;
import entity.Table;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame implements JPanelFood.Action {

    CategoryDao categoryDao;
    Category category;
    List<Category> categoryList;

    TableDao tableDao;
    Table table;
    List<Table> tableList;

    FoodDao foodDao;
    Food food;
    List<Food> foodList;

    Bill bill;
    BillInfo billInfo;
    BillDao billDao;
    List<BillInfo> billInfoList;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.categoryDao = new CategoryDao();
        this.tableDao = new TableDao();
        this.foodDao = new FoodDao();
        this.billDao = new BillDao();
        this.categoryList = categoryDao.getAll();
        this.tableList = tableDao.getAll();

        loading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jListTable = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListCategory = new javax.swing.JList<>();
        jScrollPaneFood = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("THÔNG TIN CÁ NHÂN");

        jButton3.setText("ĐĂNG XUẤT");
        jButton3.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPaneTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPaneTableMouseClicked(evt);
            }
        });

        jListTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jListTable.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListTable.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTableValueChanged(evt);
            }
        });
        jScrollPaneTable.setViewportView(jListTable);

        jListCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jListCategory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListCategory.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCategoryValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jListCategory);

        jLabel3.setText("Mã giảm giá");

        jTextField1.setText("jTextFieldVoucher");

        jLabel4.setText("Thông tin giảm giá");

        jLabel5.setText("Tổng tiền");

        jLabel6.setText("VNĐ");

        jButton4.setText("THANH TOÁN");

        jLabelTotal.setText("jLabelTotal");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(55, 55, 55)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("ORDER");

        jLabel2.setText("MENU");

        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableOrder.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTableOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableOrderKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableOrderKeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(jTableOrder);

        jLabel7.setText("BÀN ...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneFood))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneFood, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListCategoryValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCategoryValueChanged
        // TODO add your handling code here:
        category = categoryDao.findByName(jListCategory.getSelectedValue());
        foodList = foodDao.findByCategory(category.getId());
        JPanel panelFood = new JPanel();
        panelFood.setLayout(new GridLayout(foodList.size() / 6, 6));
        foodList.forEach(obj -> {
            panelFood.add(new JPanelFood(obj.getName(), obj.getPrice(), this, this));
        });
        panelFood.revalidate();
        panelFood.repaint();
        jScrollPaneFood.setViewportView(panelFood);
    }//GEN-LAST:event_jListCategoryValueChanged

    private void jScrollPaneTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPaneTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jScrollPaneTableMouseClicked

    private void jListTableValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTableValueChanged
        // TODO add your handling code here:
        table = tableDao.findByName(jListTable.getSelectedValue());
        jLabel7.setText(table.getName());
        bill = billDao.findByIdTale(table.getId());
        if (bill == null) {
            bill = new Bill();
            bill.setId_table(table.getId());
            bill.setStatus(0);
            billDao.createBill(bill);
        }
        loadingOrder(bill);

//        loadTotal();
    }//GEN-LAST:event_jListTableValueChanged

    private void jTableOrderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableOrderKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableOrderKeyPressed

    private void jTableOrderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableOrderKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int id = billInfoList.get(jTableOrder.getSelectedRow()).getId();
            billDao.deleteBillInfo(id);
            loadingOrder(bill);
        }
        

//        loadTableOrder();
//        loadTotal();
    }//GEN-LAST:event_jTableOrderKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JList<String> jListCategory;
    private javax.swing.JList<String> jListTable;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPaneFood;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void loading() {
        table = tableDao.findByName(jListTable.getSelectedValue());
        category = categoryDao.findByName(jListCategory.getSelectedValue());

        jListCategory.removeAll();
        DefaultListModel<String> dlm = new DefaultListModel<>();
        categoryList.forEach(obj -> {
            dlm.addElement(obj.getName());
        });
        jListCategory.setModel(dlm);

        jListTable.removeAll();
        DefaultListModel<String> dlmTable = new DefaultListModel<>();
        tableList.forEach(obj -> {
            dlmTable.addElement(obj.getName());
        });
        jListTable.setModel(dlmTable);

        foodList = foodDao.findByCategory(1);
        JPanel panelFood = new JPanel();
        panelFood.setLayout(new GridLayout(foodList.size() / 6, 6));
        foodList.forEach(obj -> {
            panelFood.add(new JPanelFood(obj.getName(), obj.getPrice(), this, this));
        });
        panelFood.revalidate();
        panelFood.repaint();
        jScrollPaneFood.setViewportView(panelFood);
        
        
    }

    private void loadingOrder(Bill bill) {

        jTableOrder.removeAll();
        billInfoList = billDao.getBillInfo(bill.getId());

        String columns[] = {"TÊN MÓN", "SỐ LƯỢNG", "ĐƠN GIÁ"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0);

        if (!billInfoList.isEmpty()) {
            billInfoList.forEach(obj -> {
                dtm.addRow(new Object[]{foodDao.findById(obj.getId_food()).getName(), obj.getCount(), foodDao.findById(obj.getId_food()).getPrice()});
            });

            jTableOrder.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
                int position = jTableOrder.getSelectedRow();
                if (position >= 0) {
                    billInfo = billInfoList.get(position);
                }

            });

            jTableOrder.changeSelection(0, 0, false, false);
        }

        jTableOrder.setModel(dtm);

    }

    @Override
    public void action(String name) {
        food = foodDao.findByName(name);
        
        int check = 0;
        for (BillInfo b : billInfoList) {
            if (b.getId_food() == food.getId()) {
                b.setCount(b.getCount() + 1);
                billDao.updateBillInfo(b);
                check = 1;
                break;
            }
        }
        if (check == 0) {
            BillInfo b = new BillInfo();
            b.setId_bill(bill.getId());
            b.setId_food(food.getId());
            b.setCount(1);
            billDao.createBillInfo(b);
        }
        
        loadingOrder(bill);
    }

    private void loadTotal() {
//        if (dtmOrder.getRowCount() != 0) {
//            int total = 0;
//            for (int i = 0; i < dtmOrder.getRowCount(); i++) {
//                int price = Integer.parseInt(dtmOrder.getValueAt(i, 3).toString());
//                total += price;
//            }
//            jLabelTotal.setText(String.valueOf(total));
//        } else {
//            jLabelTotal.setText("0");
//        }
    }

    private void loadTableOrder() {
//        for (int i = 0; i < dtmOrder.getRowCount(); i++) {
//            String name = dtmOrder.getValueAt(i, 0).toString();
//            Food f = foodDao.findByName(name);
//            dtmOrder.setValueAt(f.getPrice(), i, 2);
//            int amount = Integer.parseInt(dtmOrder.getValueAt(i, 1).toString());
//            dtmOrder.setValueAt(f.getPrice() * amount, i, 3);
//        }
//        jTableOrder.revalidate();
//        jTableOrder.repaint();
    }

}
